name: flet_soundbyte
description: Flet FletSoundbyte control
repository: https://github.com/MyGithubAccount/flet-soundbyte/src/flutter/flet_soundbyte
version: 0.1.0
homepage: https://github.com/MyGithubAccount/flet-soundbyte

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.27.6
  flutter:
    sdk: flutter
#  flutter_spinkit: ^5.2.1
  audioplayers: ^6.4.0
  flutter_sound: ^9.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
